---
 - name: playbook1 for exercice1 TP2
   hosts: all
   become: yes
   gather_facts: no
   tasks:
     - name: installation paquet httpd
       yum:
           name: httpd
           state: present 

     - name: demarrer et activer le service httpd 
       service:
           name: httpd
           state: started 
           enabled: yes

     - name: creation du fichier test
       copy:
           dest: /var/www/html/test 
           content: 'ceci est un simple test de playbook'
           owner: root
           group: root
           mode: 0644

     - name: test connectivité 
       uri:
         url: http://localhost:80/test
